# Header
menu:
  Root: /
  Archivos: /archives
  Github: https://github.com/luis-fuentes
  rss: /atom.xml

favicon: /favicon.png
logo: /logo-blog.png
lang: es

# Comment
# e.g disqus: seansun
disqus: luisfuentes
duoshuo: 

# Analytics
# google-analytics:
ga: UA-64770465-1
# baidu-analytics:
ba: 

# Copyright Infomation
startyear: 2012

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true

